name: spring-microsevices
services:
  kafka:
    image: 'bitnami/kafka:4.0.0'
    container_name: kafka
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  mongodb:
    image: 'bitnami/mongodb:8.0.6'
    container_name: mongodb
    hostname: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: root
  neo4j:
    image: 'neo4j:latest'
    container_name: neo4j
    hostname: neo4j
    restart: always
    ports:
      - '7474:7474'
      - '7687:7687'